function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  })[char])
}

export function renderProfileHtml(profile) {
  const name = escapeHtml(profile.name || 'Pengguna WhatsApp')
  const number = escapeHtml(profile.number || 'Tidak tersedia')
  const initials = escapeHtml((profile.name || 'U').trim().slice(0, 1).toUpperCase())
  const photo = profile.photo ? escapeHtml(profile.photo) : ''
  return `<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#F4F0E6;color:#000;font-family:system-ui,-apple-system,sans-serif}body{padding:20px}.card{max-width:360px;margin:auto;position:relative;border:4px solid #000;border-radius:16px;background:#FFF;box-shadow:8px 8px 0px #000;overflow:hidden}.cover{height:120px;background:#FF90E8;border-bottom:4px solid #000;position:relative;background-image:radial-gradient(#000 2px,transparent 2px);background-size:20px 20px}.brand{position:absolute;top:16px;left:16px;font-size:12px;font-weight:900;background:#000;color:#FFF;padding:4px 8px;border-radius:4px}.badge{position:absolute;top:16px;right:16px;font-size:12px;font-weight:900;background:#FFDE59;color:#000;border:3px solid #000;padding:4px 8px;border-radius:6px;box-shadow:3px 3px 0 #000}.body{padding:0 20px 20px}.avatar{width:90px;height:90px;margin-top:-45px;position:relative;z-index:2;display:grid;place-items:center;border:4px solid #000;border-radius:16px;background:#00E5FF;color:#000;font-size:36px;font-weight:900;box-shadow:4px 4px 0 #000;overflow:hidden}.avatar img{width:100%;height:100%;object-fit:cover;border-radius:0}.name{margin:16px 0 4px;font-size:26px;font-weight:900;line-height:1.1;letter-spacing:-.03em;overflow-wrap:anywhere}.caption{margin:0;font-weight:700;font-size:13px;color:#444}.divider{height:4px;margin:20px 0;background:#000}.label{font-size:11px;font-weight:900;letter-spacing:.1em;text-transform:uppercase;margin-bottom:12px}.row{display:flex;align-items:center;gap:12px;margin-bottom:12px;padding:12px;border:3px solid #000;border-radius:12px;box-shadow:3px 3px 0 #000}.icon{width:40px;height:40px;display:grid;place-items:center;border-radius:8px;border:3px solid #000;font-size:20px;box-shadow:2px 2px 0 #000}.meta{min-width:0}.meta small{display:block;font-weight:800;font-size:10px;text-transform:uppercase}.meta strong{display:block;font-weight:900;font-size:15px;margin-top:2px;overflow-wrap:anywhere}.foot{display:flex;justify-content:space-between;align-items:center;margin-top:20px;font-weight:900;font-size:11px;text-transform:uppercase}.dot{display:inline-block;width:12px;height:12px;margin-right:6px;border-radius:50%;background:#34C759;border:3px solid #000}
</style></head><body><main class="card"><header class="cover"><span class="brand">PROFIL WA</span><span class="badge">Neo Brutalism</span></header><section class="body"><div class="avatar">${photo ? `<img src="${photo}" alt="Foto profil" onerror="this.remove()">` : initials}</div><h1 class="name">${name}</h1><p class="caption">Wanna play some games?</p><div class="divider"></div><div class="label">Informasi Pengguna</div><div class="row" style="background: #E8F9FD"><span class="icon" style="background: #FF90E8">&#9823;</span><div class="meta"><small>Nama Tampilan</small><strong>${name}</strong></div></div><div class="row" style="background: #FFF4E6"><span class="icon" style="background: #FFDE59">&#9742;</span><div class="meta"><small>Nomor WhatsApp</small><strong>+${number}</strong></div></div><footer class="foot"><span><i class="dot"></i>Active</span><span>BOT PROFILE</span></footer></section></main></body></html>`
}
