function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  })[char])
}

export function renderProfileHtml(profile) {
  const name = escapeHtml(profile.name || 'Pengguna WhatsApp')
  const number = escapeHtml(profile.number || 'Tidak tersedia')
  const initials = escapeHtml((profile.name || 'U').trim().slice(0, 1).toUpperCase())
  const photo = profile.photo ? escapeHtml(profile.photo) : ''
  return `<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#10141d;color:#f5f7fb;font-family:system-ui,-apple-system,'Segoe UI',sans-serif}body{padding:18px}.card{max-width:360px;margin:auto;overflow:hidden;border:1px solid #293142;border-radius:26px;background:linear-gradient(155deg,#202a3a,#151b27 58%,#171c28);box-shadow:0 18px 50px #05070b99}.cover{height:145px;position:relative;background:radial-gradient(ellipse at 78% 5%,#79e3c544,transparent 42%),radial-gradient(ellipse at 8% 80%,#6389ff44,transparent 48%),linear-gradient(130deg,#29364b,#17212e)}.cover:after{content:'';position:absolute;inset:0;background-image:radial-gradient(#ffffff22 1px,transparent 1px);background-size:18px 18px;opacity:.45}.brand{position:absolute;z-index:1;top:18px;left:20px;font-size:11px;font-weight:800;letter-spacing:.2em;color:#d5e3f0}.badge{position:absolute;z-index:1;right:17px;top:16px;padding:7px 10px;border:1px solid #ffffff30;border-radius:99px;background:#10172288;font-size:10px;color:#d3e1eb}.body{padding:0 22px 22px}.avatar{width:88px;height:88px;margin-top:-46px;position:relative;z-index:2;display:grid;place-items:center;border:4px solid #19212d;border-radius:25px;background:linear-gradient(145deg,#8be2c2,#718cff);color:#111b27;font-size:36px;font-weight:900;box-shadow:0 8px 24px #0006;overflow:hidden}.avatar img{width:100%;height:100%;object-fit:cover}.name{margin:16px 0 5px;font-size:25px;line-height:1.12;letter-spacing:-.04em;overflow-wrap:anywhere}.caption{margin:0;color:#91a0b3;font-size:13px}.divider{height:1px;margin:21px 0;background:#ffffff13}.label{font-size:10px;font-weight:800;letter-spacing:.17em;color:#8393a9}.row{display:flex;align-items:center;gap:12px;margin-top:12px;padding:13px;border:1px solid #ffffff12;border-radius:15px;background:#ffffff06}.icon{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;background:#8be2c21b;color:#8be2c2;font-size:16px}.meta{min-width:0}.meta small{display:block;margin-bottom:3px;color:#8393a9;font-size:10px}.meta strong{display:block;color:#eef3fa;font-size:13px;font-weight:650;overflow-wrap:anywhere}.foot{display:flex;justify-content:space-between;align-items:center;margin-top:19px;color:#738197;font-size:10px}.dot{display:inline-block;width:7px;height:7px;margin-right:6px;border-radius:50%;background:#83e1b7;box-shadow:0 0 9px #83e1b7}
</style></head><body><main class="card"><header class="cover"><span class="brand">MY PROFILE</span><span class="badge">WHATSAPP</span></header><section class="body"><div class="avatar">${photo ? `<img src="${photo}" alt="Foto profil" onerror="this.remove()">` : initials}</div><h1 class="name">${name}</h1><p class="caption">Senang melihatmu di sini</p><div class="divider"></div><div class="label">INFORMASI AKUN</div><div class="row"><span class="icon">&#9823;</span><div class="meta"><small>Nama tampilan</small><strong>${name}</strong></div></div><div class="row"><span class="icon">&#9742;</span><div class="meta"><small>Nomor WhatsApp</small><strong>+${number}</strong></div></div><footer class="foot"><span><i class="dot"></i>Profil WhatsApp</span><span>BOT PROFILE</span></footer></section></main></body></html>`
}
